name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # WICHTIG für GHCR

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/sertacengin/web-app:latest .

    - name: Push Docker image
      run: docker push ghcr.io/sertacengin/web-app:latest
    
    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@v1.0.3
      env:
        HCLOUD_TOKEN: ${{ secrets.HETZNER_TOKEN }}
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          kubectl rollout restart deployment web